= 事前指示書
吉田 敏幸 <yostos@yostos.org>
:description: この文書は{Author}が将来自らの判断能力を失った場合、自らの意思表示の能力を失った場合に、自分に行われる終末医療および死後直後の対応について、予め希望をまとめたものです。
:lang: ja
:toc: left
:toc-title: 目次
:toclevel: 4
:imagesdir: images
:figure-caption: 図
:chapter-signifier:
:scripts: cjk
:doctype: book
:sectnumlevels: 4
:sectnums:
:source-highlighter: rouge
:rouge-style: gruvbox
:lastname: 吉田
:firstname: 敏幸
:email: yostos@yostos.org
:date: Last Change:2023-04-25 21:27:02.
:revdate: Last Change:2023-04-25 21:27:02.
:revision: 0.1.1
:revnumber: 0.1.1
:version-label: Revision


== この文書について

{description}

この文書の形式や正当性を検証する方法については、Appendixを参照。


== 医療に対する私の希望

私({author})および私の家族は、私が以下の状況となった場合には担当いただく医療関係者の皆様に下記のように考えていただようにお願いします。

.下記の希望についての発動条件
* 私が自分で意思表示ができず、以下のいずれかの状況に至った場合
    - 私の具合が悪くなり死期が近くこのまま何も治療をしなければ救命できない
    - 治療しても私が希望する健康状態までの回復は期待できない

ただし、ここに書かれたことは現在私が考えていることであり私の意思で今後変更することもあります。
上記以外の予期しない突発的な事故の場合には下記に書かれたことではなく、通常の医療をお願いします。

.医療に対する希望
. 最後を迎える場所は自宅なのか病院なのかを自身で希望を表明できない場合は、家族の妻と息子に一任します。
. 治療に際しては、医療者には以下の項目を尊重していただく思います。
.. 心肺蘇生（心臓マッサージなど）
... 回復の見込みがない場合に、心臓や呼吸が停止したときは救急蘇生処置を施さないでください。
... 不幸にも人工呼吸器が装着された場合、改善の見込みが無ければその時点で取り外して差し支えありません。
.. 栄養
... 栄養の経口摂取が不能となった場合は寿命が尽きたと考え、経管栄養、胃管、胃瘻、中心静脈栄養、末梢静脈輸液などは行わないでください。
... 点滴による水分補給も希望いたしません。
.. 輸血
... 末期がんなどによる出血などに対して展望のない輸血は不要です。
.. 鎮痛
... できるだけ自然な状態で過ごしたいと思いますが、自身で意思表示が可能な状態への回復が見込めず、客観的に痛みが酷い場合は鎮痛の副作用によらず緩和を希望します。

== 死後についての希望

私の死の直後に直接判断が必要となるであろう事項について、家族に向けて私の希望を記載しておきます。

あくまで私の希望なのであり、既にこの世にいない私よりは家族が当事者なので家族の都合を第一に考えて参考程度に見てくれればよい。

なお、ここで言う家族とは、妻、および息子のみを指します。

世の中には自分の常識から外れたことについて話し合いにならない理屈を振りかざして口出しをする人間がいるので、敢えて書いておきます。家族である両名以外の血縁を含めた第三者については、以下の事項についての意見は無用であるので口出しは遠慮いただきたい。口出しがあった場合は呪います。


=== 葬儀の希望

可能であれば、**直葬** を希望する。

臨終から骨上げまでの一般的な葬儀は以下のような流れになろう。

[plantuml]
.一般的な葬儀の流れ
----
@startuml

(*) -right-> "臨終"
-> "安置"
-> "通夜"
-> "告別式"
-> "出棺"
-> "火葬"
-> "骨上げ"
-> (*)

@enduml
----

なるべく端折りたいところではあるが、一般的には直葬を希望しても端折れるのは以下のよう「通夜」と「告別式」であろう。


[plantuml]
.直葬の流れ
----
@startuml

(*) -right-> "臨終"
-> "安置"
-> "出棺"
-> "火葬"
-> "骨上げ"
-> (*)

@enduml
----

.. 臨終から火葬まで24時間以上の時間をあける必要があるので、安置が必要となる。安置する場所は葬儀屋に任せ、葬儀会館のようなところが手間がかからないと思う。自宅だとエレベータであらぬ事になる可能性がある。
.. 納棺はこだわりはない。「古式湯灌」と「普通湯灌」があるがどちらでもよい。棺も適当なものでよい。
.. 通夜と告別式は希望しない。家族が希望する場合には、簡素に実施することは苦しからず。
.. 通夜や告別式を行う場合も家族のみで、友人や遠方の親戚の参列は不要。
.. 友人への告知は落ち着いたところでFacebookを通じてのみでよい。Facebookの追悼アカウント管理人に妻を指定しておくので、追悼プロフィールに告知を投稿して固定するようお願いする。
.. 通夜や告別式を実施する場合は、読経は不要である。雰囲気が出ないのでと家族が希望するならば、読経のみ行うも苦しからず。その場合は宗派にこだわる必要はない。
.. 死後戒名は拒否する。遠慮とかでなく拒否する。
.. 供花や香典も辞退する。

=== 遺灰処理について

骨上げ、収骨も希望しないが、関西以外の地域では収骨しないという対応は難しかろう。

.. 火葬場で収骨なしが可能であれば、遺灰など全てお任せして手ぶらで帰ってかまわない。偲ぶよすがという場合は髪の毛でも刈り取ってください。
.. 収骨が必要な場合は、最低限にとどめてよい。
.. 遺灰については公園にでも捨ててほしいところだが、法規違反となるため粉骨代行や適当なところへの納骨、自然埋葬など手間をかけずに済まてよい。
.. 大きなお寺への納骨などすぐに廃棄されるので公園に撒くほうがマシだと思うが、イベントとして家族が楽しめるのであれば苦しからず。希望はしません。
.. 墓など形に残るものは希望しない。

=== 法要について

.. 四十九日、納骨法要、開眼法要、御斎などあらゆる法要は希望しない。
.. 年忌法要、墓参りなども不要。
.. ただし、家族で集まり会食などするイベントとして希望する場合は、行うのも苦しからず。


---
{author} +
{date} +
(署名は印刷版のみとし、電子ファイルにはGnuPGでの電子署名を行います)

## Appendix


### A.1. この文書を見るには

この文書のソース(Advance-Directives.adoc)はAsciidoc記法で記述され、PDF/HTMLに変換されています。通常はソースでなく変換したPDFかHTMLを参照ください。


何らかの理由でソースを確認する場合は、adoc形式は通常のテキスト形式なので何も処理せずにエディタなどで開くと、そのまま読める形式となっています。

文書のオリジナルは以下の保管されています。

https://github.com/yostos/advance-directives


PDFファイル(Advance-Directives.pdf)については、以下のコマンドにより生成されています。

[source,sh]
.ドキュメントの生成方法
----

$ make help     #<1>

$ make pdf      #<2>

----
<1> makeの使い方を確認する
<2> PDFを生成する

ドキュメントの生成は以下のソフトウェアに依存しています。


- asciidoctor
- asciidoctor-pdf
- asciidoctor-pdf-cjk
- asccidoctor-rouge
- asciidoctor-diagram

上記のソフトウェアはそれぞれ依存するソフトウェアがありますが、
以下のコマンドで環境が整うはずです。

[source,sh]
.生成環境の整え方
----
$ gem install asciidoctor
$ gem install asciidoctor-pdf
$ gem install asciidoctor-pdf-cjk
$ gem install asciidoctor-rouge
$ gem install asciidoctor-diagram
----

詳しくは、ブログ記事「 https://log.yostos.org/2022/08/24/asciidoc/[AsciiDocで書く] 」を参照ください。また、更紗フォントを使用していますが、リポジトリーに含めています。

### A.2. この文書の正当性について

この文書には GnuPG の署名を付けておきます。

私の意思が確かに私の意思であるかを確認したい場合は、私の公開鍵を公開鍵サーバー(https://keys.openpgp.org) からダウンロードし、以下のコマンドで署名を確認してください。

私の公開鍵は、私のメールアドレス {email} で検索できます。



[source,sh]
.文書の検証方法
----
$ make verify                             # <1>

$ gpg --verify Advance-Directives.pdf.sig # <2>
----
<1> 全てのソースファイルと生成されたPDF/HTMLについて署名の整合性を確認します。
<2> 個別にファイルを確認することも可能です。これはPDFの署名の整合性を確認する例です。

NOTE: GnuPGとは「Gnu Privacy Guard」または「GPG」とも呼ばれる。公開鍵でファイルの署名を検証したり、公開鍵と秘密鍵のペアでメールの暗号化・復号化を行ったり署名を添付したりするツールです。


