= 事前指示書
吉田 敏幸 <yostos@yostos.org>
:description: この文書は{Author}が将来自らの判断能力を失った場合、自らの意思表示の能力を失った場合に、自分に行われる終末医療および死後直後の対応について、予め希望をまとめたものです。
:lang: ja
:toc: left
:toc-title: 目次
:toclevel: 4
:imagesdir: images
:figure-caption: 図
:chapter-signifier:
:scripts: cjk
:doctype: book
:sectnumlevels: 4
:sectnums:
:source-highlighter: rouge
:rouge-style: gruvbox
:lastname: 吉田
:firstname: 敏幸
:email: yostos@yostos.org
:date: Last Change:2023-04-16 21:13:26.
:revdate: Last Change:2023-04-16 21:13:26.
:revision: 0.1.1
:revnumber: 0.1.1
:version-label: Revision


== この文書について

{description}

この文書の形式や正当性を検証する方法については、Appendixを参照。


== 医療に対する私の希望

私({author})および私の家族は、私が以下の状況となった場合には
担当いただく医療関係者の皆様に下記のように考えていただようにお願いします。

.下記の希望についての発動条件
* 私が自分で意思表示ができず、以下のいずれかの状況に至った場合
    - 私の具合が悪くなり死期が近くこのまま何も治療をしなければ救命できない
    - 治療しても私が希望する健康状態までの回復は期待できない

ただし、ここに書かれたことは現在私が考えていることであり私の意思で今後変更することもあります。
上記以外の予期しない突発的な事故の場合には下記に書かれたことではなく、通常の医療をお願いします。

.医療に対する希望
. 最後を迎える場所は自宅なのか病院なのかを自身で希望を表明できない場合は、家族の
吉田裕美と吉田悠利に一任します。
. 治療に際しては、医療者には以下の項目を尊重していただく思います。
.. 心肺蘇生（心臓マッサージなど）
... 回復の見込みがない場合に、心臓や呼吸が停止したときは救急蘇生処置を施さないで
ください。
... 不幸にも人工呼吸器が装着された場合、改善の見込みが無ければその時点で取り外し
て差し支えありません。
.. 栄養
... 栄養の経口摂取が不能となった場合は寿命が尽きたと考え、経管栄養、胃管、胃瘻、
中心静脈栄養、末梢静脈輸液などは行わないでください。
... 点滴による水分補給も希望いたしません。
.. 輸血
... 末期がんなどによる出血などに対して展望のない輸血は不要です。
.. 鎮痛
... できるだけ自然な状態で過ごしたいと思います。今後も自身で意思表示が可能な状態
への
回復が見込めず、客観的に痛みが酷い場合は痛みの副作用によらず緩和を希望します。

== 死後についての希望

私の死の直後に直接判断が必要となるであろう事項について、
家族に向けて私の記載しておきます。

ここで言う家族とは、吉田裕美、および吉田悠利を指します。

両名以外の血縁による以下の事項についての意見は無用であるので、
口出しは遠慮いただきたい。


.死後の希望
. 葬儀
.. 家族のみで、友人や親戚の参列は不要。
.. 友人への告知は落ち着いたところでFacebookを通じてのみでよい。
facebookの追悼アカウント管理人に吉田裕美を指定しておくので、追悼プロフィール
に告知を投稿して固定するようお願いする。
.. 葬儀会館などを使用しなるべく手間をかけず、読経や死後戒名も不要。
ただし、家族で希望があれば読経のみ行うも苦しからず。その場合は宗派にこだわる
必要はない。
.. 告別式不要、供花や香典も辞退する。
. 遺灰
.. 遺灰についても火葬場が対応可能であれば収骨せず全て処理してしまってかまわない。
偲ぶよすがという場合は髪の毛でも刈り取ってください。
.. 遺灰処理が思うに任せず、納骨が必要な場合は粉骨代行や適当なところへの納骨、自
然埋葬など手間をかけずに済ませること。
.. 年忌法要、墓参りなども不要。親戚一同からの口出しは無用。家族で希望があれば、
年忌法要を行うのも苦しからず。


NOTE: 関西以外の地域では収骨しないという対応は難しいらしい。

---
{author} +
{date} +
(署名は印刷版のみとし、電子ファイルにはGPGでの電子署名を行います)

## Appendix


### A.1. この文書を見るには

この文書のソース(Advance-Directives.adoc)はAsciidoc記法で記述され、PDFに変換されています。

adoc形式は通常のテキスト形式なので何も処理せずにエディタなどで開くと、
そのまま読める形式となっています。

文書のオリジナルは以下の保管されています。

https://github.com/yostos/advance-directives


PDFファイル(Advance-Directives.pdf)については、以下のコマンドにより生成されています。

```sh

# makeの使い方を確認する
$ make help
# PDFを生成する
$ make pdf

```



### A.2. この文書の正当性について

この文書には GPG の署名を付けておきます。

私の意思が確かに私の意思であるかを確認したい場合は、私の公開鍵を公開鍵サーバー
(https://keys.openpgp.org) からダウンロードし、以下のコマンドで署名を確認してく
ださい。私の公開鍵は、私のメールアドレス {email} で検索できます。



```sh
# 全てのソースと生成されたファイルと署名の整合性を確認する場合は、
# 以下のコマンドで可能です。
$ make verify

# 個別のファイルの整合性を確認するには以下のように個別に確認してください。
$ gpg --verify Advance-Directives.pdf.sig
```



