= 事前指示書
吉田 敏幸 <yostos@yostos.org>
:description: この文書は{Author}が将来自らの判断能力を失った場合、自分に行われる終末医療および死後直後の対応について、予め希望をまとめたものです。
:lang: ja
:toc: left
:toc-title: 目次
:toclevel: 4
:imagesdir: images
:figure-caption: 図
:chapter-signifier:
:scripts: cjk
:doctype: book
:sectnumlevels: 4
:sectnums:
:source-highlighter: rouge
:rouge-style: gruvbox
:lastname: 吉田
:firstname: 敏幸
:email: yostos@yostos.org
:date: Last modified: 2026-09-06T10:37:21+09:00.
:revdate: Last modified: 2026-09-06T10:37:21+09:00.
:revision: 0.2.1
:revnumber: 0.2.1
:version-label: Revision


== この文書について

{description}

この文書の形式や正当性を検証する方法については、Appendixを参照してください。


== 医療に対する私の希望

私({author})および私の家族は、私が以下の状況となった場合には担当いただく医療関係者の皆様に下記のように考えていただくようお願いします。

.下記の希望についての発動条件
* 私が自分で意思表示ができず、以下のいずれかの状況に至った場合
    - 私の具合が悪くなり死期が近くこのまま何も治療をしなければ救命できない
    - 治療しても私が希望する健康状態までの回復は期待できない

ただし、ここに書かれたことは現在私が考えていることであり私の意思で今後変更することもあります。
上記以外の予期しない突発的な事故の場合には下記に書かれたことではなく、通常の医療をお願いします。

なお、上記の判断にあたっては、厚生労働省「人生の最終段階における医療・ケアの決定プロセスに関するガイドライン」等に基づき、主治医単独の判断ではなく、医療・ケアチームと家族による話し合いのプロセスを経た上で判断していただくことを希望します。

.医療に対する希望
. 最後を迎える場所は自宅なのか病院なのかを自身で希望を表明できない場合は、家族に一任します。
. 治療に際しては、医療者には以下の項目を尊重していただきたいと思います。
.. 心肺蘇生（心臓マッサージなど）
... 回復の見込みがない場合に、心臓や呼吸が停止したときは救急蘇生処置を施さないでください。
... 不幸にも人工呼吸器が装着された場合、改善の見込みが無ければその時点で取り外して差し支えありません。
.. 栄養
... 栄養の経口摂取が不能となった場合は寿命が尽きたと考え、経管栄養、胃管、胃瘻、中心静脈栄養、末梢静脈輸液などは行わないでください。
... 点滴による水分補給も希望いたしません。
.. 輸血
... 末期がんなどによる出血などに対して展望のない輸血は不要です。
.. 鎮痛
... できるだけ自然な状態で過ごしたいと思いますが、自身で意思表示が可能な状態への回復が見込めず、客観的に痛みが酷い場合は鎮痛の副作用によらず緩和を希望します。

== 死後についての希望

私の死の直後に判断が必要となるであろう事項について、特に死後のイベントについての私の希望を、家族に向けて記載しておきます。

あくまで私の希望であり、既にこの世にいない私よりは当事者である家族が自分たちの都合を第一に考えて参考程度に見ていただければと思います。

なお、ここで言う家族とは、私と生活をともにする家族のみを指し、それ以外の血縁者は含みません。

私の死にまつわるイベントは第一に私の家族のものです。
家族と私の希望以外を考慮する必要はありません。
口出ししてくる血縁を含めた第三者については、私の遺志ということで本文書を提示してください。

=== 葬儀の希望

可能であれば、**直葬** を希望します。

臨終から骨上げまでの一般的な葬儀は以下のような流れになると思います。

[plantuml]
.一般的な葬儀の流れ
----
@startuml

(*) -right-> "臨終"
-> "安置"
-> "通夜"
-> "告別式"
-> "出棺"
-> "火葬"
-> "骨上げ"
-> (*)

@enduml
----

なるべく簡略化したいところですが、一般的に直葬を希望しても省略できるのは、以下のような「通夜」と「告別式」でしょう。


[plantuml]
.直葬の流れ
----
@startuml

(*) -right-> "臨終"
-> "安置"
-> "出棺"
-> "火葬"
-> "骨上げ"
-> (*)

@enduml
----

.. 臨終から火葬まで24時間以上の時間をあける必要があるので、安置が必要となります。安置する場所は葬儀屋に任せます。葬儀会館のようなところが手間がかからないと思います。自宅の場合、エレベーターで支障が出る可能性があります。
.. 納棺にこだわりはありません。「古式湯灌」と「普通湯灌」がありますが、どちらでも構いません。棺も適当なもので構いません。
.. 通夜と告別式は希望しません。家族が希望する場合には、簡素に実施していただいて構いません。
.. 通夜や告別式を行う場合も家族のみとし、友人や遠方の親戚の参列は不要です。
.. 知人への告知は不要です。喪中はがきも不要です。
.. 通夜や告別式を実施する場合、読経は不要です。音が必要であれば、 https://www.youtube.com/@yostos-guitar[YouTubeにある自作曲]を流してもらえるとうれしいです。
「それでは雰囲気が出ない」と家族が希望するのであれば、読経のみ行っていただいても構いません。その場合、宗派にこだわる必要はありませんが、「お経／浄土真宗本願寺派門信徒勤行」などが配信サービスに音源があります。適当に流しておいていただければと思います。

.. 死後戒名は拒否します。遠慮ではなく、明確に拒否します。
.. 供花や香典も辞退します。

=== 遺灰処理について

骨上げ、収骨も希望しません。しかし、関西以外の地域では収骨しないという対応は難しいと思いますので、遺灰処理の希望について記載しておきます。

.. 火葬場で収骨なしが可能であれば、遺灰などすべてお任せして手ぶらで帰っていただいて構いません。偲ぶよすがが必要な場合は、髪の毛でも刈り取ってください。
.. 収骨が必要な場合は、最低限にとどめていただいて構いません。
.. 遺灰については公園にでも撒いてほしいところですが、法規違反となるため、粉骨代行や適当な場所への納骨、自然葬など、手間をかけずに済ませていただいて構いません。
.. 大きなお寺への納骨などは希望しませんが、イベントとして家族が楽しめるのであれば拒否はしません。
.. 墓、遺灰など、形に残るものは希望しません。

=== 法要について

.. 四十九日、納骨法要、開眼法要、御斎など、あらゆる法要は希望しません。
.. 年忌法要、墓参りなども不要です。
.. ただし、家族で集まり会食などをするイベントとして希望する場合は、行っていただいて構いません。


== デジタル遺品について

各種オンラインサービスの認証情報や、私の死後に対応が必要となる事項、
データの保管場所などについては、私の死後すぐに必要となると思いますが、
本文書には含めていません。

これらは家族のみが参照できる場所に別途まとめてあり、その所在は家族に伝えてあります。


---
{author} +
{date} +
(署名は印刷版のみとし、電子ファイルにはGnuPGでの電子署名を行います)

## Appendix


### A.1. この文書を見るには

この文書のソース(Advance-Directives.adoc)はAsciidoc記法で記述され、PDF/HTMLに変換されています。通常はソースでなく変換したPDFかHTMLを参照してください。
AsciiDocについては、ブログ記事「 https://codedchords.dev/blog/2026/07/asciidoc/[技術文書用フォーマット AsciiDoc] 」を参照してください。また、更紗フォントを使用していますが、リポジトリーに含めています。

何らかの理由でソースを確認する場合は、adoc形式は通常のテキスト形式なので何も処理せずにエディタなどで開くと、そのまま読める形式となっています。

文書のオリジナルは以下に保管されています。

https://github.com/yostos/advance-directives

- buildフォルダに生成したPDF,HTMLがあります
- docsフォルダにソースコードがあります


### A.2. この文書の正当性について

この文書には GnuPG の署名を付けておきます。

私の意思が確かに私の意思であるかを確認したい場合は、私の公開鍵を公開鍵サーバー(https://keys.openpgp.org) からダウンロードし、以下のコマンドで署名を確認してください。

私の公開鍵は、私のメールアドレス {email} で検索できます。



[source,sh]
.文書の検証方法
----
$ make verify                             # <1>

$ gpg --verify Advance-Directives.pdf.sig # <2>
----
<1> 全てのソースファイルと生成されたPDF/HTMLについて署名の整合性を確認します。
<2> 個別にファイルを確認することも可能です。これはPDFの署名の整合性を確認する例です。

NOTE: GnuPGとは「Gnu Privacy Guard」または「GPG」とも呼ばれます。公開鍵でファイルの署名を検証したり、公開鍵と秘密鍵のペアでメールの暗号化・復号化を行ったり署名を添付したりするツールです。


